# Generated by Django 4.2.19 on 2025-07-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_created_category_updated_notes_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.category'),
        ),
    ]
